export const projects = [{
        title: 'Coder Buddy',
        description: "Using Javascript, Bootstrap & Firebase . It has links to all Coding platforms and shows every Ongoing as well as Upcoming Coding Competitions",
        image: '/images/1.jpeg',
        tags: ['Javascript', 'Bootsrap', 'Firebase'],
        source: 'https://github.com/Anshuman4492/Coder-Buddy',
        visit: 'https://anshuman4492.github.io/Coder-Buddy/',
        id: 0,
    },
    {
        title: 'Countdown Timer',
        description: "A decreasing timer that shows how much time left for any event.By default,it shows the time left in the New Year's Eve",
        image: '/images/2.png',
        tags: ['JavaScript'],
        source: 'https://github.com/Anshuman4492/Countdown-Timer',
        visit: 'https://anshuman4492.github.io/Countdown-Timer/',
        id: 1,
    },
    // {
    //     title: 'WebRTC App',
    //     description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
    //     image: '/images/3.jpg',
    //     tags: ['React', 'WebRTC'],
    //     source: 'https://google.com',
    //     visit: 'https://google.com',
    //     id: 2,
    // },
    // {
    //     title: 'Unichat',
    //     description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    //     image: '/images/4.jpg',
    //     tags: ['React', 'ChatEngine', 'Firebase'],
    //     source: 'https://google.com',
    //     visit: 'https://google.com',
    //     id: 3,
    // },
];

export const TimeLineData = [
    { year: 2017, text: 'Started my journey', },
    { year: 2018, text: 'Worked as a freelance developer', },
    { year: 2019, text: 'Founded JavaScript Mastery', },
    { year: 2020, text: 'Shared my projects with the world', },
    { year: 2021, text: 'Started my own platform', },
];